version: "3.3"

services:
  app:
    build: .
    command: ["npm", "start"]
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/code
      - ./src:/code/django-bananas
      - /code/node_modules
